### ISSUE TITLE
`go get github.com/golang/x/sys/unix` doesn't work

### ISSUE THREAD

**Issue by evandrix** [EricLagerg/go-coreutils#106]
Unlike the other commands as specified in the README doc, this one prompts me for my username & password:
````
Username for 'https://github.com': 
Password for 'https://<useraname>@github.com': 
````

Then it subsequently fails with:
````
remote: Repository not found.
fatal: repository 'https://github.com/golang/x/' not found
package github.com/golang/x/sys/unix: exit status 128
```

**Comment by EricLagerg** [comment]
Thanks. Fixed with https://github.com/EricLagerg/go-coreutils/commit/898d64fba2b48ed380760a1877c301bb520ab6a4

**Comment by EricLagerg** [comment]
I should also go through and re-updated all the required libraries as well...
