### ISSUE TITLE
Merge gonix into go-coreutils

### ISSUE THREAD

**Issue by polegone** [EricLagerg/go-coreutils#2]
I'm ready to start merging.

**Comment by polegone** [comment]
I'm working on the copyright notices now. Give me about 15 minutes.

**Comment by polegone** [comment]
Complete. Check my code when you're ready.

**Comment by EricLagerg** [comment]
base64
basename
cal
nl
tee
seq
touch

**Comment by polegone** [comment]
These are the apps you want to merge?

**Comment by EricLagerg** [comment]
Yep! The license isn't a big deal... I don't think it matters.

**Comment by polegone** [comment]
OK, I'll revert the changes I made to mine (so they will all be uniform) and close that issue I just made. Give me another few minutes.

**Comment by polegone** [comment]
Alright. How do I start with this? I've been using the web UI the whole time.

**Comment by EricLagerg** [comment]
Which OS do you use?

**Comment by polegone** [comment]
Debian Linux.

**Comment by polegone** [comment]
I know how to clone a repo, but not how to send things back.

**Comment by EricLagerg** [comment]
Ahhhh. Fork mine, clone it, copy over your files into their respective directories, add, commit, push, go to your fork, and do this: https://help.github.com/articles/creating-a-pull-request/

**Comment by polegone** [comment]
OK, I'll try.

**Comment by polegone** [comment]
I sent you the pull request.

**Comment by EricLagerg** [comment]
Sweet, got it!

**Comment by polegone** [comment]
Since I'm not going to be working on gonix anymore, would you like me to transfer my repo to you?

**Comment by EricLagerg** [comment]
If you want to, sure. Yours does have 600 stars, and that does reflect well on your GH account :-)

**Comment by polegone** [comment]
Ah, it's fine, I don't care much about this account...
I'm not really the right person to manage an open source project.

**Comment by EricLagerg** [comment]
It's up to you!
